import React, { useState, useEffect } from 'react';
import { 
  Sparkles, 
  Calendar, 
  PenTool, 
  Target, 
  Package, 
  ArrowRight, 
  Download, 
  Copy, 
  RefreshCw,
  Plus,
  CheckCircle2,
  Image as ImageIcon
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import api from '../api/config';
import toast from 'react-hot-toast';

type StudioMode = 'calendar' | 'content' | 'product' | 'ads';

interface ContentPost {
  id: string;
  title: string;
  platform: string;
  post_type: string;
  content_text?: string;
  hashtags?: string;
  image_prompt?: string;
  status: 'idea' | 'generated' | 'scheduled' | 'published';
}

const MarketingStudio: React.FC = () => {
  const [activeMode, setActiveMode] = useState<StudioMode>('calendar');
  const [isLoading, setIsLoading] = useState(false);
  const [calendar, setCalendar] = useState<any>(null);
  const [generatedResult, setGeneratedResult] = useState<any>(null);

  // Form states for Lab
  const [labTopic, setLabTopic] = useState('');
  const [labPlatform, setLabPlatform] = useState('Instagram');
  const [labTone, setLabTone] = useState('احترافية وفاخرة');

  // Form states for Product Description
  const [productName, setProductName] = useState('');
  const [targetAudience, setTargetAudience] = useState('salons');

  const handleLabGenerate = async () => {
    if (!labTopic) return toast.error('يرجى كتابة موضوع المنشور');
    setIsLoading(true);
    try {
      const res = await api.post('/content-studio/generate-post', { 
        custom_topic: labTopic,
        platform: labPlatform,
        tone: labTone
      });
      setGeneratedResult(res.data.post);
      toast.success('تم توليد المحتوى الإبداعي!');
    } catch (err) {
      toast.error('فشل توليد المحتوى');
    } finally {
      setIsLoading(false);
    }
  };

  const handleRegenerate = () => {
    if (activeMode === 'content' && generatedResult?.id) {
       generatePostContent(generatedResult);
    } else if (activeMode === 'content' && labTopic) {
       handleLabGenerate();
    } else if (activeMode === 'product' && productName) {
       // Re-trigger product generation
       document.getElementById('product-gen-btn')?.click();
    } else {
       toast.error('لا يوجد محتوى حالي لإعادة توليده');
    }
  };

  const downloadContent = () => {
    if (!generatedResult) return;
    
    const content = `
O2OEG AI Marketing Content
--------------------------
Topic: ${labTopic || generatedResult.title || ''}
Platform: ${labPlatform || generatedResult.platform || ''}

Content:
${generatedResult.content_text || generatedResult.description || generatedResult.caption || ''}

Hashtags:
${Array.isArray(generatedResult.hashtags) ? generatedResult.hashtags.join(' ') : (generatedResult.hashtags || '')}

Image AI Prompt:
${generatedResult.image_prompt || ''}
--------------------------
Generated by O2OEG Marketing Studio
    `;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `O2OEG_Post_${new Date().getTime()}.txt`;
    link.click();
    toast.success('تم تحميل الملف بنجاح');
  };

  useEffect(() => {
    if (activeMode === 'calendar') {
      fetchLatestCalendar();
    }
  }, [activeMode]);

  const fetchLatestCalendar = async () => {
    setIsLoading(true);
    try {
      const res = await api.get('/content-studio/calendar');
      if (res.data.length > 0) {
        setCalendar(res.data[0]);
      }
    } catch (err) {
      console.error('Failed to fetch calendar', err);
    } finally {
      setIsLoading(false);
    }
  };

  const generateWeeklyPlan = async () => {
    setIsLoading(true);
    try {
      const res = await api.post('/content-studio/generate-plan');
      setCalendar(res.data.calendar);
      toast.success('تم توليد الخطة الأسبوعية بنجاح!');
    } catch (err) {
      toast.error('فشل توليد الخطة. تأكد من تفعيل خدمة الذكاء الاصطناعي.');
    } finally {
      setIsLoading(false);
    }
  };

  const generatePostContent = async (post: ContentPost) => {
    setIsLoading(true);
    try {
      const res = await api.post('/content-studio/generate-post', { post_id: post.id });
      setGeneratedResult(res.data.post);
      toast.success('تم توليد المحتوى بنجاح!');
      fetchLatestCalendar(); // Refresh status
    } catch (err) {
      toast.error('فشل توليد المحتوى');
    } finally {
      setIsLoading(false);
    }
  };

  const copyToClipboard = (text: string) => {
    if (!text) return;
    navigator.clipboard.writeText(text);
    toast.success('تم النسخ للحافظة');
  };

  return (
    <div className="space-y-8 text-right rtl" dir="rtl">
      {/* Header & Mode Selector */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div>
          <h2 className="text-3xl font-black text-white">استوديو التسويق الذكي</h2>
          <p className="text-sm text-white/40 mt-1">مدعوم بذكاء O2OEG لتحويل أفكارك إلى نتائج ملموسة</p>
        </div>
        
        <div className="bg-white/5 border border-white/10 p-1.5 flex gap-1 rounded-2xl">
          {[
            { id: 'calendar', icon: Calendar, label: 'الجدول الأسبوعي' },
            { id: 'content', icon: PenTool, label: 'مختبر المحتوى' },
            { id: 'product', icon: Package, label: 'وصف المنتجات' },
            { id: 'ads', icon: Target, label: 'استراتيجية الإعلانات' },
          ].map((mode) => (
            <button
              key={mode.id}
              onClick={() => {
                setActiveMode(mode.id as StudioMode);
                setGeneratedResult(null);
              }}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-bold transition-all duration-300 ${
                activeMode === mode.id 
                ? 'bg-fuchsia-600 text-white shadow-lg shadow-fuchsia-600/20' 
                : 'text-white/40 hover:text-white/80 hover:bg-white/5'
              }`}
            >
              <mode.icon size={14} />
              {mode.label}
            </button>
          ))}
        </div>
      </div>

      {/* Main Content Area */}
      <div className="min-h-[500px]">
        <AnimatePresence mode="wait">
          {activeMode === 'calendar' && (
            <motion.div
              key="calendar"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="space-y-6"
            >
              {!calendar ? (
                <div className="bg-white/5 border border-white/10 rounded-[32px] p-20 text-center flex flex-col items-center gap-6">
                  <div className="w-20 h-20 rounded-3xl bg-fuchsia-500/10 flex items-center justify-center text-fuchsia-500">
                    <Sparkles size={40} className="animate-pulse" />
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-white">ابدأ رحلة النجاح التسويقي</h3>
                    <p className="text-sm text-white/40 max-w-sm mx-auto mt-2">قم بتوليد خطة محتوى ذكية لمدة 7 أيام مخصصة لجمهورك وعملك.</p>
                  </div>
                  <button 
                    onClick={generateWeeklyPlan}
                    disabled={isLoading}
                    className="bg-fuchsia-600 hover:bg-fuchsia-500 text-white font-black px-10 py-4 rounded-2xl transition-all shadow-lg shadow-fuchsia-600/20 flex items-center gap-3"
                  >
                    {isLoading ? 'جاري بناء الخطة...' : 'توليد خطة أسبوعية الآن'}
                    {!isLoading && <ArrowRight size={18} />}
                  </button>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                  {calendar.posts.map((post: any, idx: number) => (
                    <motion.div 
                      key={post.id}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: idx * 0.05 }}
                      className="group bg-white/5 border border-white/10 p-6 rounded-3xl hover:border-fuchsia-500/30 transition-all relative overflow-hidden"
                    >
                       <div className="absolute top-0 right-0 w-16 h-16 bg-gradient-to-br from-fuchsia-600/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                      
                      <div className="flex justify-between items-center mb-4">
                        <span className="text-[10px] font-black uppercase tracking-widest text-fuchsia-400 bg-fuchsia-500/10 px-2 py-1 rounded-lg">
                          {post.platform}
                        </span>
                        {post.status === 'generated' && <CheckCircle2 size={16} className="text-green-400" />}
                      </div>
                      
                      <h4 className="font-bold text-white text-sm leading-relaxed mb-6">{post.title}</h4>
                      
                      <button 
                        onClick={() => {
                          setActiveMode('content');
                          if (post.status === 'idea') {
                            generatePostContent(post);
                          } else {
                            setGeneratedResult(post);
                          }
                        }}
                        className="w-full py-3 bg-white/5 hover:bg-fuchsia-600 hover:text-white rounded-xl text-[10px] font-black transition-all border border-white/5 hover:border-fuchsia-500 flex items-center justify-center gap-2"
                      >
                        {post.status === 'generated' ? 'مشاهدة المحتوى' : 'توليد النص'}
                        <ArrowRight size={12} />
                      </button>
                    </motion.div>
                  ))}
                  <button 
                    onClick={generateWeeklyPlan}
                    className="bg-transparent border-2 border-dashed border-white/10 rounded-3xl p-6 flex flex-col items-center justify-center gap-3 text-white/20 hover:text-fuchsia-400 hover:border-fuchsia-500/40 transition-all group"
                  >
                    <Plus size={32} className="group-hover:scale-110 transition-transform" />
                    <span className="text-xs font-bold">تجديد الخطة</span>
                  </button>
                </div>
              )}
            </motion.div>
          )}

          {activeMode === 'content' && (
            <motion.div
              key="content"
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              className="grid grid-cols-1 lg:grid-cols-2 gap-8"
            >
              <div className="bg-white/5 border border-white/10 p-8 rounded-[32px] space-y-6">
                <div className="flex items-center gap-3 text-fuchsia-400">
                  <PenTool size={24} />
                  <h3 className="font-bold text-white text-lg">مختبر المحتوى الإبداعي</h3>
                </div>
                
                <div className="space-y-4">
                  <div className="space-y-2">
                    <label className="text-xs text-white/40 mr-2">موضوع المنشور</label>
                    <textarea 
                      value={labTopic}
                      onChange={(e) => setLabTopic(e.target.value)}
                      placeholder="عن ماذا تريد التحدث اليوم؟..."
                      className="w-full bg-black/40 border border-white/10 rounded-2xl px-5 py-4 text-sm text-white h-32 focus:outline-none focus:border-fuchsia-500/50 transition-all resize-none"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <label className="text-xs text-white/40 mr-2">المنصة</label>
                      <select 
                        value={labPlatform}
                        onChange={(e) => setLabPlatform(e.target.value)}
                        className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-white focus:outline-none appearance-none"
                      >
                        <option>Instagram</option>
                        <option>Facebook</option>
                        <option>WhatsApp</option>
                      </select>
                    </div>
                    <div className="space-y-2">
                      <label className="text-xs text-white/40 mr-2">نبرة الصوت</label>
                      <select 
                        value={labTone}
                        onChange={(e) => setLabTone(e.target.value)}
                        className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-white focus:outline-none appearance-none"
                      >
                        <option>احترافية وفاخرة</option>
                        <option>ودودة ومرحة</option>
                        <option>حماسية</option>
                      </select>
                    </div>
                  </div>

                  <button 
                    onClick={handleLabGenerate}
                    disabled={isLoading}
                    className="w-full py-4 bg-fuchsia-600 text-white font-black rounded-2xl hover:bg-fuchsia-500 transition-all flex items-center justify-center gap-2 mt-4 shadow-lg shadow-fuchsia-600/20"
                  >
                    {isLoading ? 'جاري التوليد...' : 'توليد المحتوى بالذكاء الاصطناعي'} <Sparkles size={18} />
                  </button>
                </div>
              </div>

              <div className="bg-white/5 border border-white/10 p-8 rounded-[32px] flex flex-col gap-6">
                <div className="flex justify-between items-center">
                  <h3 className="font-bold text-fuchsia-400 text-sm tracking-widest uppercase">النتيجة المقترحة</h3>
                  <div className="flex gap-2">
                    <button 
                      onClick={() => generatedResult && copyToClipboard(generatedResult.content_text || generatedResult.caption)} 
                      title="نسخ النص"
                      className="p-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/40 hover:text-white transition-all"
                    >
                      <Copy size={16} />
                    </button>
                    <button 
                      onClick={handleRegenerate}
                      title="إعادة التوليد"
                      className="p-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/40 hover:text-white transition-all"
                    >
                      <RefreshCw size={16} className={isLoading ? 'animate-spin' : ''} />
                    </button>
                    <button 
                      onClick={downloadContent}
                      title="تحميل كملف"
                      className="p-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/40 hover:text-white transition-all"
                    >
                      <Download size={16} />
                    </button>
                  </div>
                </div>

                <div className="flex-1 bg-black/40 border border-white/5 rounded-2xl p-6 text-white text-sm leading-loose whitespace-pre-wrap min-h-[200px]">
                  {generatedResult ? (generatedResult.content_text || generatedResult.caption || 'تم توليد المحتوى بنجاح ولكن النص فارغ...') : 'اطلب من الذكاء الاصطناعي توليد نص المنشور ليظهر هنا...'}
                </div>

                {generatedResult?.hashtags && (
                  <div className="flex flex-wrap gap-2">
                    {(typeof generatedResult.hashtags === 'string' 
                      ? generatedResult.hashtags.split(' ') 
                      : Array.isArray(generatedResult.hashtags) 
                        ? generatedResult.hashtags 
                        : []
                    ).filter(Boolean).map((tag: string, i: number) => (
                      <span key={i} className="text-[10px] font-bold text-cyan-400 bg-cyan-500/5 px-2 py-1 rounded-lg border border-cyan-500/10">
                        {tag.startsWith('#') ? tag : `#${tag}`}
                      </span>
                    ))}
                  </div>
                )}

                {generatedResult?.image_prompt && (
                  <div className="bg-cyan-500/5 border border-cyan-500/20 p-4 rounded-2xl">
                    <p className="text-[10px] font-black text-cyan-400 uppercase tracking-widest mb-2 flex items-center gap-2">
                      <ImageIcon size={12} /> Image AI Prompt (English)
                    </p>
                    <p className="text-[11px] text-white/60 italic leading-relaxed">{generatedResult.image_prompt}</p>
                  </div>
                )}
              </div>
            </motion.div>
          )}

          {activeMode === 'product' && (
            <motion.div
              key="product"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="grid grid-cols-1 lg:grid-cols-2 gap-8"
            >
              <div className="bg-white/5 border border-white/10 p-8 rounded-[32px] space-y-6">
                <div className="flex items-center gap-3 text-cyan-400">
                  <Package size={24} />
                  <h3 className="font-bold text-white text-lg">وصف المنتجات الاحترافي</h3>
                </div>
                
                <div className="space-y-4">
                  <div className="space-y-2">
                    <label className="text-xs text-white/40 mr-2">اسم المنتج</label>
                    <input 
                      type="text"
                      value={productName}
                      onChange={(e) => setProductName(e.target.value)}
                      placeholder="مثال: زيت المعالجة السحرية بالأرجان"
                      className="w-full bg-black/40 border border-white/10 rounded-xl px-5 py-3 text-sm text-white focus:outline-none focus:border-cyan-500/50 transition-all"
                    />
                  </div>
                   <div className="space-y-2">
                    <label className="text-xs text-white/40 mr-2">الجمهور المستهدف</label>
                    <select 
                      value={targetAudience}
                      onChange={(e) => setTargetAudience(e.target.value)}
                      className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-white focus:outline-none appearance-none"
                    >
                      <option value="salons">أصحاب الصالونات والمحترفين (B2B)</option>
                      <option value="customers">العملاء النهائيين (B2C)</option>
                    </select>
                  </div>
                </div>

                <button 
                  onClick={async () => {
                    setIsLoading(true);
                    try {
                      const res = await api.post('/content-studio/generate-product-description', {
                        product_name: productName,
                        target_audience: targetAudience
                      });
                      setGeneratedResult(res.data);
                    } catch (err) {
                      toast.error('فشل توليد الوصف');
                    } finally {
                      setIsLoading(false);
                    }
                  }}
                  disabled={isLoading || !productName}
                  className="w-full py-4 bg-cyan-600 text-white font-black rounded-2xl hover:bg-cyan-500 transition-all flex items-center justify-center gap-2 mt-4 shadow-lg shadow-cyan-600/20"
                >
                  {isLoading ? 'جاري كتابة القصة...' : 'صناعة القصة التسويقية'} <Sparkles size={18} />
                </button>
              </div>

              <div className="bg-white/5 border border-white/10 p-8 rounded-[32px] flex flex-col gap-6">
                 {generatedResult && generatedResult.description ? (
                   <div className="space-y-6">
                      <h3 className="text-2xl font-black text-white">{generatedResult.title}</h3>
                      <p className="text-sm text-white/70 leading-loose whitespace-pre-wrap">{generatedResult.description}</p>
                      
                      <div className="space-y-3 pt-4 border-t border-white/5">
                        <h4 className="text-xs font-bold text-white/40 uppercase tracking-widest">أبرز المميزات:</h4>
                        <div className="grid grid-cols-1 gap-2">
                          {generatedResult.features?.map((f: string, i: number) => (
                            <div key={i} className="flex items-center gap-3 bg-white/5 p-3 rounded-xl">
                              <CheckCircle2 size={14} className="text-cyan-400" />
                              <span className="text-xs text-white/80">{f}</span>
                            </div>
                          ))}
                        </div>
                      </div>

                      <div className="mt-6 flex items-center justify-between bg-cyan-500/10 border border-cyan-500/20 p-4 rounded-2xl">
                        <span className="text-xs font-black text-cyan-400">{generatedResult.cta}</span>
                        <div className="flex gap-2">
                          <button onClick={() => copyToClipboard(generatedResult.description)} className="p-2 bg-white/10 hover:bg-white/20 rounded-lg transition-all text-white/60"><Copy size={16} /></button>
                          <button onClick={downloadContent} className="p-2 bg-white/10 hover:bg-white/20 rounded-lg transition-all text-white/60"><Download size={16} /></button>
                        </div>
                      </div>
                   </div>
                 ) : (
                   <div className="flex-1 flex flex-col items-center justify-center text-white/20 gap-4 text-center">
                      <Package size={48} />
                      <p className="text-sm font-bold">ادخل اسم المنتج لبدء صناعة المحتوى التسويقي</p>
                   </div>
                 )}
              </div>
            </motion.div>
          )}

          {activeMode === 'ads' && (
            <motion.div
              key="ads"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-8"
            >
              <div className="bg-gradient-to-br from-amber-500/10 via-orange-500/5 to-transparent border border-amber-500/20 p-10 rounded-[40px] text-center space-y-6 relative overflow-hidden">
                <div className="absolute top-0 right-0 w-64 h-64 bg-amber-500/5 blur-[100px] rounded-full"></div>
                <div className="w-20 h-20 rounded-3xl bg-amber-500/20 flex items-center justify-center mx-auto text-amber-500 relative z-10">
                  <Target size={40} />
                </div>
                <div className="relative z-10">
                  <h2 className="text-3xl font-black text-white">مستشار الحملات الممولة</h2>
                  <p className="text-white/60 max-w-xl mx-auto mt-4">قم بتحليل أفضل طريقة لصرف ميزانيتك الإعلانية للوصول لنتائج حقيقية لصالونك أو منتجاتك.</p>
                </div>
                <button 
                  onClick={async () => {
                    setIsLoading(true);
                    try {
                      const res = await api.post('/content-studio/generate-ads-strategy');
                      setGeneratedResult(res.data);
                      toast.success('تم تحليل الاستراتيجية بنجاح');
                    } catch (err) {
                      toast.error('فشل التحليل');
                    } finally {
                      setIsLoading(false);
                    }
                  }}
                  disabled={isLoading}
                  className="px-12 py-4 bg-amber-500 text-black font-black rounded-2xl hover:bg-amber-400 transition-all shadow-xl shadow-amber-500/20 relative z-10"
                >
                  {isLoading ? 'جاري التحليل الاستراتيجي...' : 'توليد خطة الاستهداف'}
                </button>
              </div>

              {generatedResult?.strategy && (
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  {(Array.isArray(generatedResult.strategy) ? generatedResult.strategy : []).map((item: any, idx: number) => (
                    <motion.div 
                      key={idx}
                      initial={{ opacity: 0, scale: 0.9 }}
                      animate={{ opacity: 1, scale: 1 }}
                      transition={{ delay: idx * 0.1 }}
                      className="bg-white/5 border border-white/10 p-8 rounded-[32px] space-y-4 hover:border-amber-500/30 transition-all group"
                    >
                      <div className="w-12 h-12 rounded-2xl bg-white/5 flex items-center justify-center text-amber-500 group-hover:scale-110 transition-transform">
                        {idx === 0 ? <Target size={24} /> : idx === 1 ? <Package size={24} /> : <RefreshCw size={24} />}
                      </div>
                      <h4 className="font-bold text-white text-lg">{item.title}</h4>
                      <p className="text-sm text-white/40 leading-relaxed">{item.description}</p>
                    </motion.div>
                  ))}
                </div>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default MarketingStudio;
